### Listar vendas

POST https://localhost:5001/api/venda/create
Content-Type: application/json

{
    "ProdutoId" : 1,
    "Cliente" : "joao",
    "itens" : "Percy",
    "PagamentoId" : 1,
    "CarrinhoId" : ""
}
####listar
GET https://localhost:5001/api/venda/list